RESET ROLE;
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT SELECT ON TABLE public.vehicles TO authenticated;
GRANT SELECT ON TABLE public.locations TO authenticated;
GRANT SELECT ON TABLE public.dashboard_stock_summary TO authenticated;
GRANT SELECT ON TABLE public.location_stock_report TO authenticated;
GRANT SELECT ON TABLE public.model_stock_report TO authenticated;
GRANT SELECT ON TABLE public.finance_stock_report TO authenticated;
GRANT SELECT ON TABLE public.dealer_code_stock_report TO authenticated;
GRANT SELECT ON TABLE public.gate_movement_report TO authenticated;
